### ISSUE TITLE
Sonic Crackers shows bugged title card

### ISSUE THREAD

**Issue by RepellantMold** [Clownacy/clownmdemu#15]
Yesterday I decided to try this game, and [did a video showing it on YouTube](https://youtu.be/Le1-RcvE1JE), and I decided that I'd bring it here since another person also found the same issue;

The title card on levels bug out, it causes dots on World 2s background in attractions, and it causes some of the tether graphics to become black squares which carry over into the field stages (though they show up fine there if you start on them via "SELECT".)

The Z80 sound driver also doesn't seem to cause the game to crash ([the problematic line](https://github.com/Not-So-Filter/scrackers-disasm/blob/d8677e1fd768ca58a86a23ce548bd99bf2feecb1/sound/Z80.asm#L396)) Ala inaccurate emulators.

A weird strip of 3 white squares will also show up in the "SELECT" menu if you can manage to trigger the alternative SEGA screen as shown in this screenshot;

![image](https://github.com/Clownacy/clownmdemu/assets/76079717/55579b38-5dc0-417f-9a68-ce460781e5fb)

Here's a video comparison of the title card..

Bugged:

https://github.com/Clownacy/clownmdemu/assets/76079717/a8d72d28-17bb-49ec-873c-ea42dccb95da

The intended result (using BlastEm):

https://github.com/Clownacy/clownmdemu/assets/76079717/05dd5b4f-a6c9-448d-b27d-34ce7136c4fb

**Comment by Clownacy** [comment]
Thanks, that was a great test for some edge-cases in VDP command latching! Crackers' DMA function is bugged, uploading only half of a VDP address command.
