### ISSUE TITLE
The tinyfiledialogs submodule used is not FreeBSD-compatible

### ISSUE THREAD

**Issue by jfolker** [Clownacy/clownmdemu#2]
... But I made a fork of it that is.
... And I even fixed a latent bug on other platforms.

https://github.com/jfolker/tinyfiledialogs

The original author doesn't update frequently, can you use my version instead? I managed to build clownmdemufrontend (FreeBSD, Clang) and even play Sonic 2 XL on it successfully.

**Comment by Clownacy** [comment]
I've switched to your version in 6e98f6d4ad3c7df21a596b6101b9ca5d4a96f3a6. Thanks for the fixes!
