### ISSUE TITLE
You can port these Sonic's games AND movian application to Wii U?

### ISSUE THREAD

**Issue by wikiblog0** [Clownacy/clownmdemu#4]
Do you think it would be possible for you to port these three Sonic games:

Sonic 3 A.I.R
Sonic Nexus
Sonic Robo Blast 2
The Sonic 3 A.I.R has its source code on github, just google it and I think there is a port for Switch.

The Sonic Nexus decompile is in the Rubberduckycooly repository and is also based on RSDK so it can be ported to the Wii U.

Sonic Robo Blast 2 has its source code on its website and it would be interesting to see the port of the latest version of SRB2 on Wii U.

Finally, I wanted to ask you if it is possible if you can compile and adapt to Wii U, the movian application. It is a multimedia center that is for PS3 and PC and an attempt was made a long time ago to make a port for Wii. Maybe you can use the Wii port source code to make the Wii U port, especially since streaming services on Wii U are going to end soon.

You can find the Movian Wii source code in the wikiblog0 github repository. And the original source code on the movian website.

Link: https://github.com/wikiblog0/movian-wii-wiiu
I appreciate your contributions to the Wii U scene.

Greetings

**Comment by Clownacy** [comment]
I'm not interested in porting games that I won't play: I ported Sonic CD and Sonic Mania because I wanted to play them on my Wii U, but I don't want to play Sonic 3 A.I.R., Sonic Nexus, or Sonic Robo Blast 2. Likewise for Movian: I don't use it, so I have no interest in porting it.

**Comment by wikiblog0** [comment]
Thanks for reply my issue.
