### ISSUE TITLE
Decremented writes to CRAM aren't inverted

### ISSUE THREAD

**Issue by RealMalachi** [Clownacy/clownmdemu#40]
So you remember that fix you did for Jim Power? This is basically that for CRAM, but with no commercial examples as far as I'm aware.
For a text printing routine I've made, I used a longword decrement write to CRAM via the data ports, to save a few bytes. Abbreviated code below:
```m68k
	lea	vdpctrl,a5
	lea	(a5),a4		; dec to data port
	move.l	#vdpComm(0,CRAM_WRITE),(a5)
	move.l	d2,-(a4)	; dec to data port (written values are word-inverted)
```
On real hardware and all other emulators I've tested, this results in the word values in d2 being written out of order, or "word-inverted". The only other thing I know that shares this behaviour is the AtGames Firecore of all things. [Here's a rom to test this on](https://github.com/Clownacy/clownmdemu/files/14504605/rom.md)

**Comment by Clownacy** [comment]
That should be fixed by the Jim Power fix. The ROM works fine in the newest commits, just not v0.6.
