### ISSUE TITLE
Missing 68K file

### ISSUE THREAD

**Issue by Brainulator9** [Clownacy/clownmdemu#5]
At one point, `m68k.c` references `m68k/gen.c`, which does not appear to exist. I take it `m68k/generator.c` was meant?

**Comment by Clownacy** [comment]
I need to update the build instructions. The `m68k` folder contains the tool to generate that file. It outputs to `stdout`, so it can be piped to `gen.c` on the command line.

**Comment by paulmcquad** [comment]
After I pipe to `gen.c` and compile. I get the following error when loading a rom.

ERROR: Attempted to write to ROM address 0x0

**Comment by Clownacy** [comment]
This emulator's compatibility isn't great right now: it's tested with Sonic and Puyo Puyo but not much else. What game are you trying to play?

**Comment by Brainulator9** [comment]
Silly me, I didn't even _see_ the generated executable be built because I didn't think to look for it (I've been using Visual Studio 2019 to build this). Feel free to remove it if need be.
